[package]
name = "bitonic-sorter"
version = "0.1.0"
authors = ["psato <forhighlow@gmail.com>"]
edition = "2018"

[dependencies]

[[bin]]
name = "first"
path = "src/first.rs"

[[bin]]
name = "second"
path = "src/second.rs"

[[bin]]
name = "thrid"
path = "src/thrid.rs"

